---
rules:
  at-rule-empty-line-before: ["always", except: ["after-same-name"], ignoreAtRules: ["import", "include", "charset"]]
  at-rule-name-case: lower
  at-rule-semicolon-space-before: never

  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always-multi-line
  block-closing-brace-newline-before: always-multi-line
  block-closing-brace-space-before: always-single-line

  block-opening-brace-newline-after: always-multi-line
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: never

  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-block-no-duplicate-properties: true
  declaration-block-semicolon-space-before: never
  declaration-block-semicolon-space-after: always-single-line
  declaration-colon-space-after: never
  declaration-colon-space-before: never

  indentation: tab

  length-zero-no-unit: true

  media-feature-colon-space-after: never
  media-feature-colon-space-before: never
  media-feature-name-case: lower
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always

  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  property-case: lower
  property-no-unknown: true

  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-list-comma-space-after: always
  selector-list-comma-space-before: never
  selector-pseudo-class-case: lower
  selector-type-case: lower

  string-quotes: single
  unit-case: lower
  unit-no-unknown: true

  value-list-comma-newline-after: never-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always
  value-list-comma-space-before: never
ignoreFiles:
  - "**/*.jsx"
  - "**/*.js"
  - "**/*.tsx"
  - "**/*.ts"